---
title: "MIDCAB in DM"
output: github_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

Script to import and clean, reformat the dataset for MICAB outcome according to preoperative diabetes mellitus. 



```{r get the data}

library(easypackages)
libraries(c("tidyverse","rms","Hmisc","survival",
            "tableone", "readxl","survminer"))

# getting the dataset.

df <- read_csv("D:\\MIDCAB_DM\\midcab_dm.csv")

# str(df)

df %>% count(cad)

```

- keep only patients with SVD.

```{r}

df1 <- df %>% filter(cad == 1) 

# now df1 contains only LIMA - LAD patients here.

# glimpse(df1)

df1 %>% count(diabetes)

# here we have 346 patients with DM and 1110 without.

df1 %>% count(ohga)

df1 %>% count(insulin)

# we also have diet treated DM.

df1$diet_rx = with(df1, ifelse(diabetes == 1 & ohga == 1 & insulin == 0 , 1, 0))

df1 %>% count(diet_rx)

# so for the dm patients, make a var for treatment. diet = 1, ohga = 2, insulin = 3

df1$treat <- with(df1, ifelse(diabetes == 1 & diet_rx == 1, 1, 
                              ifelse(diabetes == 1 & ohga == 1, 2,
                                     ifelse(diabetes == 1 & insulin == 1, 3, 0))))


df1 %>% count(treat)


df1$treat = factor(df1$treat, levels = c(0,1,2,3),
                   labels = c("no_dm","oral","meds","insulin"))


df1$itdm <- with(df1, ifelse(diabetes == 1 & insulin == 1, 2,
                             ifelse(diabetes == 1 & insulin == 0, 1, 0)))

df1$itdm = factor(df1$itdm, levels = c(0,1,2),
                  labels = c("no_dm","non_itdm","itdm"))


```

Now to look at the outcome briefly, before cleaning the data.

```{r}

df1$survyears = (1 + df1$Survival_days)/365.24

s <- survfit(Surv(survyears, Died_total) ~ treat, data = df1)

s2 <- survfit(Surv(survyears, Died_total) ~ diabetes, data = df1)

s3 <- survfit(Surv(survyears, Died_total) ~ itdm, data = df1)

```

```{r,fig.height= 8,fig.width=8}


ggsurvplot(s, conf.int = T,risk.table = T,
           censor.size = 0)


ggsurvplot(s2, conf.int = T,risk.table = T,
           censor.size = 0)


ggsurvplot(s3, conf.int = T,risk.table = T,
           censor.size = 0)


```

- clean the variables, need to first change many -9 to missing.



