---
title: "MIDCAB_DM1"
author: "Salil V Deo"
date: "2/7/2021"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```


Script to import and clean, reformat the dataset for MICAB outcome according to preoperative diabetes mellitus. 



```{r get the data}

library(easypackages)
libraries(c("tidyverse","rms","Hmisc","survival",
            "tableone", "readxl","survminer","naniar"))

# getting the dataset.

df <- read_csv("D:\\MIDCAB_DM\\midcab_dm2.csv")

# str(df)

df %>% count(cad)

```

- keep only patients with SVD.

```{r}

df1 <- df %>% filter(cad == 1) 

# now df1 contains only LIMA - LAD patients here.

# glimpse(df1)

df1 %>% count(diabetes)

# here we have 346 patients with DM and 1110 without.

df1 %>% count(ohga)

df1 %>% count(insulin)

# we also have diet treated DM.

df1$diet_rx = with(df1, ifelse(diabetes == 1 & ohga == 1 & insulin == 0 , 1, 0))

df1 %>% count(diet_rx)

# so for the dm patients, make a var for treatment. diet = 1, ohga = 2, insulin = 3

df1$treat <- with(df1, ifelse(diabetes == 1 & diet_rx == 1, 1, 
                              ifelse(diabetes == 1 & ohga == 1, 2,
                                     ifelse(diabetes == 1 & insulin == 1, 3, 0))))


df1 %>% count(treat)


df1$treat = factor(df1$treat, levels = c(0,1,2,3),
                   labels = c("no_dm","oral","meds","insulin"))


df1$itdm <- with(df1, ifelse(diabetes == 1 & insulin == 1, 2,
                             ifelse(diabetes == 1 & insulin == 0, 1, 0)))

df1$itdm = factor(df1$itdm, levels = c(0,1,2),
                  labels = c("no_dm","non_itdm","itdm"))


```

Now to look at the outcome briefly, before cleaning the data.

```{r}

df1$survyears = (1 + df1$Survival_days)/365.24

s <- survfit(Surv(survyears, Died_total) ~ treat, data = df1)

s2 <- survfit(Surv(survyears, Died_total) ~ diabetes, data = df1)

s3 <- survfit(Surv(survyears, Died_total) ~ itdm, data = df1)

```

```{r,fig.height= 8,fig.width=8}


ggsurvplot(s, conf.int = T,risk.table = T,
           censor.size = 0)


ggsurvplot(s2, conf.int = T,risk.table = T,
           censor.size = 0)


ggsurvplot(s3, conf.int = T,risk.table = T,
           censor.size = 0)


```

- -9 replaced to missing using excel earlier.
- check

```{r}

describe(df1$bmi)

```

- all -9 replace with NA for all columns.

- table 1.

```{r}



vars <- c( "time_period",  "age", "sex", 
 "bmi", "diabetes", "ohga", "insulin", "newer_antidm", 
"preop_aspirin", "preop_plavix",  "preop_creat_mg", 
"Preop_ dialysis", "htn", "pah", "smoke", "hyperlip", 
"copd", "pvd", "lvef", "lvfuncion", "ekg", "priority", "critical_state", 
"preop_cpr", "preop_vent", "cad", "lmca_d", "prior_pci", "pci_vessel")


factors <- c( "time_period",  "sex", 
  "diabetes", "ohga", "insulin", "newer_antidm", 
"preop_aspirin", "preop_plavix",  
"Preop_ dialysis", "htn", "pah", "smoke", "hyperlip", 
"copd", "pvd",  "lvfuncion", "ekg", "priority", "critical_state", 
"preop_cpr", "preop_vent", "cad", "lmca_d", "prior_pci", "pci_vessel")


t1 <- tableone::CreateTableOne(vars = vars, factorVars = factors,
                               strata = c("diabetes"),
                               data = df1)

print(t1, nonnormal = c("age","preop_creat_mg"))


```

- table 2 operative details.

```{r}


df1$pump_used <- with(df1, ifelse(cpb_time == 0, 0 ,1))

df1 %>% count(convert_onpump)

df1 %>% count(pump_used)

describe(df1$cpb_time)


df1 %>% count(cpb_time)


vars <- c("prior_pci", "preop_mi", "inc_revasc", "preop_stroke", "preop_cva", 
"preop_cs", "prior_ohs",  "log_euroscore", 
 "convert_onpump", "on_bh", "convert_sternotomy", 
"surg_time", "cpb_time", "clamp_time", "postop_locas", "post_iabp", 
"post_ecmo", "post_mi", "postop_cpr", "postop_af", "post_bypass_revise" ,"pump_used")

factors <- 
  c("prior_pci", "preop_mi", "inc_revasc", "preop_stroke", "preop_cva", 
"preop_cs", "prior_ohs",  
 "convert_onpump", "on_bh", "convert_sternotomy", 
 "postop_locas", "post_iabp", 
"post_ecmo", "post_mi", "postop_cpr", "postop_af", "post_bypass_revise" ,"pump_used")

t2 <- tableone::CreateTableOne(vars = vars,
                               factorVars = factors,
                               strata = c("diabetes"),
                               data = df1)

print(t2)




```






